#!/bin/bash
set -e

INFLUX_CMD="influx -host 127.0.0.1 -username ${INFLUXDB_ADMIN_USER} -password ${INFLUXDB_ADMIN_PASSWORD} -execute "

$INFLUX_CMD "CREATE DATABASE ${SECOND_DB}"
$INFLUX_CMD "GRANT ALL PRIVILEGES ON ${SECOND_DB} TO ${INFLUXDB_USER}"
$INFLUX_CMD "SHOW DATABASES"

